name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v3 # or v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-not-allowed: '["status","wontfix"]'
          default-labels: '["triage"]'
